/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>
#include"led.h"
#include"systick.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

extern volatile uint32_t xtick;
void SysTick_Handler(void)
{
	xtick++;
}
int main(void)
{
	LedInit(LED_GREEN);
	SysTick_Config(SystemCoreClock/1000);


	while(1)
	{
		LedToggle(LED_GREEN);
		SystickDelayms(1000);

	}

	return 0;

}

